spring:
  application:
    name: discovery
  main:
    web-application-type: reactive
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://config-server:8888}
      enabled: ${CONFIG_SERVER_ENABLED:false}
    gateway:
      routes:
        # Soccer Service - 전체 선수 조회 (우선순위 1: 정확한 경로)
        - id: soccer-players-all
          uri: lb://soccer
          predicates:
            - Path=/soccer/players/all
          filters:
            - StripPrefix=1
        
        # Soccer Service - Players 전체 (우선순위 2)
        - id: soccer-players
          uri: lb://soccer
          predicates:
            - Path=/soccer/players/**
          filters:
            - StripPrefix=1
        
        # Soccer Service - Search 엔드포인트 (players/all로 리라이트)
        - id: soccer-search
          uri: lb://soccer
          predicates:
            - Path=/soccer/search
          filters:
            - RewritePath=/soccer/search, /players/all
        
        # Soccer Service - 일반 라우팅 (우선순위 3)
        - id: soccer-service
          uri: lb://soccer
          predicates:
            - Path=/soccer/**
          filters:
            - StripPrefix=1
        
        # User Service 라우팅
        - id: user-service
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=0
        
        # Company Service 라우팅
        - id: company-service
          uri: lb://company
          predicates:
            - Path=/company/**
          filters:
            - StripPrefix=0
        
        # Common Service 라우팅
        - id: common-service
          uri: lb://common
          predicates:
            - Path=/common/**
          filters:
            - StripPrefix=0
      
      # CORS 전역 설정
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://ui-server:3000"
              - "http://localhost:3001"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      
      # Discovery Client 설정 (Eureka와 통합)
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME:discovery-client}